M48
; DRILL file {KiCad 7.0.5} date Sun Feb  4 15:02:55 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-02-04T15:02:55-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
%
G90
G05
T1
X91.96Y-48.85
X91.96Y-95.8
X116.47Y-48.85
X116.47Y-95.8
T0
M30
