M48
; DRILL file {KiCad 7.0.5} date Fri Dec 29 19:04:11 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-12-29T19:04:11-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
%
G90
G05
T1
X84.544Y-69.235
X84.544Y-116.185
X109.054Y-69.235
X109.054Y-116.185
T0
M30
